# Generated by Django 3.2.7 on 2021-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
    ]
