# Generated by Django 3.2.7 on 2021-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.BooleanField(default=True),
        ),
    ]
